### ISSUE TITLE
`SSL_VERIFY_PEER` mode is not set using `SSL_CTX_set_verify()`, which may cause MITM attack

### ISSUE THREAD

**Issue by Zero0one1** [nondeterministic/mailfilter#1]
OpenSSL doesn't check if the certificate has an invalid chain of trust, so `SSL_connect()` can return 1 even if the SSL certificate is invalid. The user must call OpenSSL APIs like the first way in the below in order to terminate the program when the verification fails. Otherwise, check the peer certificate like the second way.
```cpp
// first way
ctx = SSL_CTX_new();
SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, ...); // 
ssl = SSL_new(ctx);
SSL_connect(ssl);

// second way
ctx = SSL_CTX_new(method);
ssl = SSL_new(ctx);
SSL_connect(ssl);
cert = SSL_get_peer_certificate(ssl);
if (cert){
   if (SSL_get_verify_result(ssl)==X509_V_OK){
      ...
   }
}
```
PS, [document ](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_verify.html)of `SSL_VERIFY_PEER`. 
There is a misuse in `socket.cc`. `SSL_CTX_new` lies in L124, `SSL_new` lies in L159, and `SSL_connect` lies in L176. But there is no `SSL_CTX_set_verify` or `SSL_get_peer_certificate`. Therefore, it may be attacked by man-in-the-middle attack.
https://github.com/nondeterministic/mailfilter/blob/34e0eee036eb493aaf1f0b6c366ed135a482ebe2/src/socket.cc#L111-L182

**Comment by nondeterministic** [comment]
Thanks for raising this. I haven't looked at that code in *many* years, and will need some time to get back into it. I take it, your code examples already include some kind of solution? It would be helpful, if you could elaborate a bit (or even create a patch/PR/etc.?!). Many thanks again!

**Comment by nondeterministic** [comment]
I'm just reading the docs here a little bit and from what I gather, it's not quite as you described it above. I believe, it would have to be either 1) additional program functionality to provide a user's client certificate (how many users would do that anyway for email?) **OR** 2) it needs to be `SSL_VERIFY_NONE` instead of `SSL_VERIFY_PEER`. As I'm not in a position with a lot of time on my hands for extending relatively old programs, I'd prefer fixing mailfilter rather than extending it, i.e. 2) over 1). But I'd like to make sure that my reasoning is correct, before I take on that task. Do you have any further insights on this?

**Comment by nondeterministic** [comment]
Thanks again. If you like, give the snapshot in branch `add-ssl-verification-1` a try, where some rudimentary SSL certificate validation takes place now. I haven't had a chance to thoroughly test it yet, nor the time to add a switch where one can disable it (e.g., to explicitly allow for a self-signed certificate).

**Comment by nondeterministic** [comment]
OK, I have added a "-s" switch to skip the verification of SSL certificates upon request, and have updated the doc, version numbers,etc. This is now, kind of, a release candidate. If you can, check it out and let me know if you find any issues with it.

**Comment by nondeterministic** [comment]
OK, code merged to master. I will close this as taken care of. Thanks again for notification!
